/***************************************************************
 ** Copyright (C) 2016 by Andrew Shakinovsky
 **
 ** You may also use this code under the terms of the 
 ** GPL v3 (see www.gnu.org/licenses).
 ** STOCHAS IS PROVIDED "AS IS" WITHOUT ANY WARRANTY, AND ALL 
 ** WARRANTIES, WHETHER EXPRESSED OR IMPLIED, INCLUDING 
 ** MERCHANTABILITY AND FITNESS FOR PURPOSE, ARE DISCLAIMED.
 ***************************************************************/

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#include <JuceHeader.h>

// the version.h file is auto-generated by CMake (see version.h.in)
#include "version.h"

// current version of serialization
#define SEQ_SERIALIZE_CURRENT_VERSION  1

// used for properties file
#define SEQ_APP_NAME "stochas"
#define SEQ_CO_NAME  "AudioVitamins"

// for help button
#define SEQ_HELP_URL  "https://stochas.org/documentation/"
#define SEQ_WEBSITE_URL  "https://stochas.org"

#define SEQ_RESIZE_MSG "UI was resized. Depending on your host application, you might need to restart Stochas to properly adjust the window size"

// add some code to get around cubase behavior where it actually starts play position prior to
// where the cursor is when user hits play. if any issues arise, disable this to see if the workaround
// code is the cause. its a hack because it assumes that we will get process block called while we are
// not playing
#define CUBASE_HACKS 1

/*======CONSTANTS RELATED TO INTERACTING WITH PROB, VELOCITY AND NOTES==========*/
/* probabilities:
in poly mode are 0..100 where 0 is off, and 100 is always on
in mono mode are 0..high val where 0 is off, and the following applies
(each is double the preceding one)
*/
#define SEQ_PROB_LOW_VAL      25    
#define SEQ_PROB_MED_VAL      50
#define SEQ_PROB_HIGH_VAL     100
#define SEQ_PROB_NEVER        0     // never play unless chain
#define SEQ_PROB_OFF          -1    // off
#define SEQ_PROB_ON           100   // always on val (only valid in poly mode)
#define SEQ_NOTE_OFF          -1    // note value that represents "off"

#define SEQ_PROB_NEVER_TEXT   "--C--" // never
#define SEQ_PROB_OFF_TEXT     "Off"
#define SEQ_PROB_ON_TEXT      "On"
#define SEQ_PROB_LOW_TEXT     "Low"
#define SEQ_PROB_MED_TEXT     "Med"
#define SEQ_PROB_HIGH_TEXT    "High"

// default velocity when new steps are placed
#define SEQ_VELOCITY_DEFAULT  127
// default probability for mono
#define SEQ_PROB_DEFAULT_MONO 20
// default probability for poly
#define SEQ_PROB_DEFAULT_POLY 100

// when clicking velocity, it will toggle through these steps before hitting max (127)
#define SEQ_VELOCITY_STEP_1   35
#define SEQ_VELOCITY_STEP_2   70
#define SEQ_VELOCITY_STEP_3   95

// mouse sensitivity default. higher value means less sensitive
#define SEQ_MOUSE_SENSE_DEFAULT 4   
// max mouse sensitivity (ie least sensitive value)
#define SEQ_MOUSE_SENSE_MAX   10

#define SEQ_MOUSE_AXIS_SENSE  8     // how much the user must drag the mouse before an axis is guessed

#define SEQ_POS_OFFSET_MIN    -500
#define SEQ_POS_OFFSET_MAX    500

// ui scaling
#define SEQ_UI_SCALE_DEFAULT  100
#define SEQ_UI_SCALE_MIN      50
#define SEQ_UI_SCALE_MAX      200

// duty cycle in % (101 is legato)
#define SEQ_DUTY_MIN          5
#define SEQ_DUTY_MAX          200   // anything above 100% is legato
#define SEQ_DUTY_INTERVAL     5
#define SEQ_DUTY_DEFAULT      100

/*======CONSTANTS RELATED TO LIMITS IN THE ENGINE==============================*/
// The GGD editor keeps a 1/16 storage grid but can now hold long multi-bar
// patterns without relying on the original 8-bit step ceiling.
#define SEQ_MIN_STEPS         1 // also min steps per measure
#define SEQ_MAX_STEPS         1024
#define SEQ_DEFAULT_NUM_STEPS 16
#define SEQ_MAX_STEPS_PER_MEASURE 32
// max rows we'd ever have is a chromatic progression of 0-127 (last row is off row)
#define SEQ_MAX_ROWS          129
#define SEQ_MAX_VISIBLE_ROWS  25
#define SEQ_MIN_ROWS          2  // we need one for the off row
// max patterns
#define SEQ_MAX_PATTERNS      8
// max layers
#define SEQ_MAX_LAYERS        4

// max number of source cells for a column of targets (each column shares the array)
#define SEQ_MAX_CHAIN_SOURCES 48

#define SEQ_CHAIN_FLAG_USED   1
// a chain is effective when the source cell triggered in the last cycle.
// if the NEGSRC is set, then it negates this, and it becomes effective when the source
// cell did not trigger. The effect of a chain is that the target cell will be triggered
// unless the NEGTGT is set in which case it will never trigger
#define SEQ_CHAIN_FLAG_NEGTGT 2     // do not trigger target cell when chain is effective
#define SEQ_CHAIN_FLAG_NEGSRC 4     // in effect when source cell was NOT triggered

#define SEQ_NUM_CLOCK_DIVS    7     // number of clock divider values
#define SEQ_MIN_CLOCK_DIV     1     // min numerator
#define SEQ_DEFAULT_CLOCK_DIV 16    // default numerator
#define SEQ_MAX_CLOCK_DIV     64    // max numerator
#define SEQ_CLOCK_DENOM       16    // clock divider denominator

// max num future midi events to hold (includes note on as well as note off events)
#define SEQ_MAX_MIDI_EVENTS   48
#define SEQ_DEFAULT_MIDI_CHAN 1
#define SEQ_DEFAULT_MAX_POLY  25

#define SEQ_POLY_BIAS_MIN     -99
#define SEQ_POLY_BIAS_MAX     99

#define SEQ_MAX_HUMAN_VELOCITY 100
#define SEQ_MAX_HUMAN_LENGTH   100
#define SEQ_MAX_HUMAN_POSITION 50

#define SEQ_MIN_SWING          -50
#define SEQ_MAX_SWING          50

// maximum notes in a chord (see scale.cpp)
#define SEQ_MAX_CHORD_COUNT 7

// number of note names that exist (C..B) and number of octaves
// note that for display purposes we will offset the octave by the user's preference
// which can be -2, -1 or 0
// internally, octaves start at 0 always. So we refer to them as internal octave and display octave
#define SEQ_NUM_NOTE_NAMES    12
#define SEQ_NUM_OCTAVES       11
#define SEQ_BASE_OCT_LOW      -2    // lowest selectable octave - low bound
#define SEQ_BASE_OCT_HIGH     0     // lowest selectable octave - high bound
#define SEQ_BASE_OCT_DEFAULT  -1    // default for the above two
#define SEQ_DEFAULT_OCTAVE    3     // default initial octave (internal octave number - 0 based)
#define SEQ_DEFAULT_SCALE     "Chromatic"
#define SEQ_DEFAULT_KEY       "C"
#define SEQ_DEFAULT_LAYER_NAME "<layer name>"
#define SEQ_DEFAULT_PAT_NAME   "<pattern name>"

#define SEQ_KEY_NAME_MAXLEN   3     // holds the text of a key name
#define SEQ_SCALE_NAME_MAXLEN 33    // holds the text of a scale name
#define SEQ_NOTE_NAME_MAXLEN  5     // holds a full note name eg C#-1, A# 5 or G# 10
#define SEQ_MAX_NOTELABEL_LEN 16    // maximum custom name (label, not actual note) for a note (excl terminator)
#define SEQ_LAYER_NAME_MAXLEN 15    // max len for layer name
#define SEQ_PATTERN_NAME_MAXLEN 15  // max len for layer name

#define SEQ_MAX_RETRIGGER     8     // maximum retriggers for a cell

// for midi passthru option and respond
#define SEQ_MIDI_PASSTHRU_NONE      1
#define SEQ_MIDI_PASSTHRU_UNHANDLED 2
#define SEQ_MIDI_PASSTHRU_ALL       3
#define SEQ_MIDI_RESPOND_NO         0
#define SEQ_MIDI_RESPOND_YES        1

// note length range
#define SEQ_NOTE_LENGTH_MIN 1
#define SEQ_NOTE_LENGTH_MAX 100

// standalone bpm range
#define SEQ_STANDALONE_BPM_MIN 20
#define SEQ_STANDALONE_BPM_MAX 300
#define SEQ_DEFAULT_STANDALONE_BPM 120

// maximum number of mapping items
#define SEQ_MAX_MIDI_MAPPING 128

// note source values
#define SEQ_NOTE_SOURCE_CUSTOM 1
#define SEQ_NOTE_SOURCE_STANDARD 2

// autoplay values
#define SEQ_PLAYMODE_AUTO    0
#define SEQ_PLAYMODE_INSTANT 1
#define SEQ_PLAYMODE_QUANT   2

// old-style keyboard mapping data constants retained for compatibility
#define SEQ_KEY_MAP_MAX 128

// notification values shared between processor and UI
#define SEQ_NOTIFY_HOST 1
#define SEQ_NOTIFY_UI   2

#endif
